const pre = 'LIST/'
export const SET = pre + 'SET'
export const SET_PLAYLIST = pre + 'SET_PLAYLIST'
export const SET_FILE_EXISTS = pre + 'SET_FILE_EXISTS'
export const SET_FILE_LOADING = pre + 'SET_FILE_LOADING'
