const pre = 'PLAYER/'

export const INIT = pre + 'INIT'
export const STATE = pre + 'STATE'
export const TRACK = pre + 'TRACK'
export const TIME = pre + 'TIME'
export const PLAYING = pre + 'PLAYING'
export const SHUFFLE = pre + 'SHUFFLE'
export const REPLAY = pre + 'REPLAY'
export const SHUFFLE_SKIP = pre + 'SHUFFLE_SKIP'
export const RESET = pre + 'RESET'
