export const PLAYBACK_INIT = 'PLAYBACK_INIT'
export const PLAYBACK_STATE = 'PLAYBACK_STATE'
export const PLAYBACK_TRACK = 'PLAYBACK_TRACK'
export const PLAYBACK_TIME = 'PLAYBACK_TIME'
export const PLAYING = 'PLAYING'
export const SHUFFLE = 'SHUFFLE'
export const REPLAY = 'REPLAY'